# Generated by Django 4.2.6 on 2023-10-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PDFUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.TextField()),
                ("upload_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "last_accessed_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("size", models.IntegerField()),
            ],
        ),
    ]
